### ISSUE TITLE
Big Reactors

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#25] opened 2015-07-29 01:47 UTC
I was using mystcraft to find the fluid yellorium page. I found one and made a few yellorium worlds. I pumped out a bedrockium drum worth of fluid yellorium but when I try to use any fluid pipe to pipe it into basins to turn it into blocks it won't work. I can pipe it into different drums etc. It just won't let me pipe it into a basin. In every other pack I have played I can pipe it into basins from tinkers and turn it into blocks. Can you please fix this?

**Comment by Amaxter** [comment] 2015-07-29 01:53
Hmm, that's a good one, I'm going to call in xJon to see if he knows what's going on here.

**Comment by thegam3report** [comment] 2015-07-29 01:53
Thanks man.

**Comment by thegam3report** [comment] 2015-07-29 02:04
To make this easier for you I have researched it and found that the mod Another One Bites The Dust is what allows for integration for processing with different mods such as tinker's construct.

**Comment by Amaxter** [comment] 2015-07-29 02:05
This I know, but thanks for the effort :)

**Comment by thegam3report** [comment] 2015-07-29 02:06
Is AOBD in the pack?

**Comment by Amaxter** [comment] 2015-07-29 02:07
Oh wait, I just derped, it's not. I manage five modpack and most of them have that mod, thanks for pointing it out lol. I guess I'll add it next update as it won't make a big gameplay difference for those wishing to stay true to the series.

**Comment by thegam3report** [comment] 2015-07-29 02:10
Thanks. That's what I was thinking. Also it just makes things work together more smoothly. The people that don't know about AOBD won't even have any idea it's in the pack anyways :)

**Comment by Amaxter** [comment] 2015-07-29 16:22
Has been added.

**Comment by thegam3report** [comment] 2015-07-29 16:45
I tried to do the fluid yellorium thing with the update and it still isn't working.

**Comment by Amaxter** [comment] 2015-07-29 16:46
Odd, let me reassign Jon.

**Comment by thegam3report** [comment] 2015-07-29 16:47
Thanks.

**Comment by xJon** [comment] 2015-07-29 16:58
How did you pump the yellorium into the drum?

**Comment by thegam3report** [comment] 2015-07-29 17:00
Ender-thermic Pump into a ender tank. Then used a transfer node to pump it into the bedrockium drum. I tried using fluid conduits from ender io to pump it into the basins, I've tried transfer node (liquids) and the fluiduct from thermal dynamics.

**Comment by xJon** [comment] 2015-07-29 17:01
So basically you can move the liquid and there is the liquid yellorium but you can't move it with pipes?

**Comment by thegam3report** [comment] 2015-07-29 17:01
I can move it with pipes just not to the basin.
To move it to the drum etc I can use all 3 pipes I mentioned but those 3 won't work for the basin. I even put it in my smeltery and tried to dump it into a basin and that didnt even work.

**Comment by xJon** [comment] 2015-07-29 17:04
So basically the issue is that you can't put liquid yellorium into the Tinkers' Constructs casting basin?

**Comment by thegam3report** [comment] 2015-07-29 17:06
yes

**Comment by xJon** [comment] 2015-07-29 17:15
Are you able to put the liquid yellorium into the casting table (and make ingots)?

**Comment by thegam3report** [comment] 2015-07-29 17:15
I wasn't able to before this update but I will try again.

**Comment by xJon** [comment] 2015-07-29 17:16
Before the update it wouldn't work, obviously, because we didn't have AOBD. You should try again. Update us here.

**Comment by thegam3report** [comment] 2015-07-29 17:16
Sure

**Comment by thegam3report** [comment] 2015-07-29 17:21
Nope doesn't work.

**Comment by whitepyros** [comment] 2015-07-30 00:59
I think this might be because TiCon doesnt register liquid yellorium as a molten metal, im not even sure it does with Extra TiC either

**Comment by Amaxter** [comment] 2015-07-30 01:00
It works with other packs. I've tested myself.

**Comment by whitepyros** [comment] 2015-07-30 01:02
with extra tic or another one bites the dust?

**Comment by Amaxter** [comment] 2015-07-30 01:02
No Extra TiC, just AOBD.

**Comment by whitepyros** [comment] 2015-07-30 01:03
thegam3report can you post a screenshot of how your pumping the liquid into the basins

**Comment by Amaxter** [comment] 2015-07-30 01:03
I tried myself, and it doesn’t work, it’s a really odd issue. I’ve contacted the mod author of AOBD.

**Comment by thegam3report** [comment] 2015-07-30 01:08
I dont need to post a pic right since amaxter knows what I'm talking about right?

**Comment by Amaxter** [comment] 2015-07-30 01:08
Yeah, I do. No need.

**Comment by thegam3report** [comment] 2015-07-30 01:08
Thanks

**Comment by thegam3report** [comment] 2015-07-30 01:09
Ye i've done this before in FTB Infinity for example. So I know how to do it.

**Comment by xJon** [comment] 2015-07-30 11:34
We investigate if it has anything to do with the latest build of IndustrialCraft2.

**Comment by Amaxter** [comment] 2015-07-30 13:36
I tested, it's not IC2

**Comment by Amaxter** [comment] 2015-08-02 02:22
Just an update, I haven't given up, still contacting the mod author and attempting to find a fix to the issue :)

**Comment by thegam3report** [comment] 2015-08-02 02:56
Alright :)

**Comment by Amaxter** [comment] 2015-08-02 20:25
According to the mod author of AOBD
"I tried testing it with AOBD, Tinker's Construct, Big Reactors, and Industrial Craft 2. I was able to cast yellorium just right, so my guess is that you either have some config wrong or some other mod is somehow breaking the recipe.

I'll download your pack and try to run it :3

Edit: Downloaded and ran your pack. I was able to melt down Yellorite Ore in the smeltery, and i could cast it into ingots and blocks lol So... it works for me... =P"
So I believe you're just doing it wrong. Make sure you know how the smeltery works :P

**Comment by thegam3report** [comment] 2015-08-02 20:41
It is fluid yellorium pumped out of a mystcraft world I have done it in packs like ftb infinity with the same 4 mods and was successful. I know how a smeltery works that is just silly.

**Comment by thegam3report** [comment] 2015-08-02 20:44
So it's not an issue with melting down ore and putting it into basins. I could have just pulverized and redstone furnaced it. I thought I mentioned that I pumped an entire bedrockium drum of fluid yellorium out of a mystcraft world with an ender-thermic pump.

**Comment by Amaxter** [comment] 2015-08-02 20:45
Ah, I don’t recall the details. Could you please tell that to the mod author on http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293528-aobd-2-process-all-the-ores ?

**Comment by thegam3report** [comment] 2015-08-02 20:58
Sure I'll try to figure this out with him

**Comment by xJon** [comment] 2015-08-02 21:04
@thegam3report Does the liquid that you found in a Mystcraft dimension have a block form?

**Comment by thegam3report** [comment] 2015-08-02 21:05
the page is called fluid yellorium block

**Comment by thegam3report** [comment] 2015-08-02 21:06
obviously if I found yellorium blocks then I would just quarry them and there wouldn't be an issue.

**Comment by xJon** [comment] 2015-08-02 21:15
@thegam3report It might be an issue of Mystcraft, that is generating the wrong type of liquid, or AOBD, that doesn't support that Mystcraft generates.
Probably a bit of both.
You should contact the authors of both mods, but it's not a problem with the modpack.
![image](https://cloud.githubusercontent.com/assets/8945347/9028052/a1f45dae-3974-11e5-8cfb-db5399835b82.png)

**Closed by xJon** 2015-08-02 21:15 UTC

**Comment by thegam3report** [comment] 2015-08-02 21:23
No because that is the type of liquid I used in FTB Infinity and it works. The one ur showing in ur picture is molten yellorium and completely irrelevant.

**Comment by Amaxter** [comment] 2015-08-02 22:17
Again, talk to the mod author of AOBD. No one else has complained about this, it's beyond our control (I didn't mess with the configs for Big Reactors and AOBD, neither does FTB Infinity)

**Comment by thegam3report** [comment] 2015-08-02 23:20
I found the solution. It wasn't an issue with AOBD. You made this a lot harder then It had to be. I did some googling and compared the mods between this pack and ftb infinity and I found that ftb infinity has extraTIC Which is extra tinker's construst. This allows you to pipe the fluid yellorium into basins and turn it into blocks. So will you be adding extraTIC for the increased integration with tinkers and other mods in the pack. Again it doesn't change the gameplay at all just makes the the mods in the pack work together better.

**Comment by Amaxter** [comment] 2015-08-02 23:22
I'm sorry if I made it a lot harder than it needed to be, but as a busy individual who develops several modpacks and manages servers for many of them I don't have all the time to research everything, so I hope you understand that next time :P. Glad you found the fix, I suspected it was Extra TiC as well but I'd been told it's not what I want. I'll likely add it for the next release.

**Comment by thegam3report** [comment] 2015-08-02 23:25
Thanks Amaxter. I am just glad to have found the solution which is a win/win for everyone.

**Comment by Amaxter** [comment] 2015-08-02 23:26
Just checked, Extra TiC doesn't mention support for big reactors anywhere I've found, and as sparklez doesn't have it in his series I suppose I won't be needing it. Both xJon and he mod author of AOBD have reported it works fine and neither one had Extra TiC installed. You can add it yourself and test if you're convinced, but normal yellorite smelts and casts just fine :)

**Comment by thegam3report** [comment] 2015-08-02 23:34
It's not for normal yellorite. it is for the fluid yellorium block that u can get in mystcraft worlds. The fluid yellorium block is whats inside the fuel rods of reactors. I tested with extraTIC already and it worked. So I guess I am just forced to not update again. If you want to see for yourself, grab a drum of fluid yellorium not molten and it will not work. I understand molten yellorium is from when you melt down yellorite ore but that isn't what I am talking about. AOBD is what adds the ability to melt down the yellorite in a big reactor.

**Comment by Amaxter** [comment] 2015-08-02 23:38
Ok, then I'll consider it.

**Comment by thegam3report** [comment] 2015-08-02 23:39
Alright.
